'use strict';

/** renderer — JSON schema output → plain-text email body. Empty sections skipped. */

const DISCLAIMER = '\n\n———\n⚠️ This summary was generated by AI (SiteScribe). It may contain inaccuracies, misattributions, or omissions. Always verify critical details, action items, and participant names against the attached transcript or your own notes. Do not rely on this summary as a legal or official record.';
const FOOTER = '\n\n—SiteScribe' + DISCLAIMER;

function bullets(arr) {
  if (!arr || !arr.length) return '';
  return arr.filter(Boolean).map((x) => `- ${typeof x === 'string' ? x : JSON.stringify(x)}`).join('\n');
}

function section(emoji, title, content) {
  if (!content || !content.trim()) return '';
  return `${emoji} ${title}\n${content}`;
}

function join(parts) { return parts.filter(Boolean).join('\n\n') + FOOTER; }

function tldr(d) {
  const raw = d.tldr || d.executive_summary || d.gist || '';
  if (raw) return section('⚡', 'TLDR', raw);
  if (d.summary) { const s = d.summary.split(/[.!?]\s/).slice(0, 2).join('. ').trim(); if (s && s !== d.summary) return section('⚡', 'TLDR', s + '.'); }
  return '';
}

function renderMeeting(d) {
  const parts = [];
  parts.push(tldr(d));
  if (d.summary) parts.push(section('📝', 'SUMMARY', d.summary));
  if (d.metadata?.participants?.length) parts.push(section('👥', 'PARTICIPANTS', d.metadata.participants.join(', ')));
  if (d.topics?.length) {
    const t = d.topics.map((tp) => {
      let s = tp.name || '';
      if (tp.summary) s += (s ? '\n' : '') + tp.summary;
      if (tp.key_points?.length) s += '\n' + tp.key_points.map((p) => `  - ${p}`).join('\n');
      return s;
    }).filter(Boolean).join('\n\n');
    parts.push(section('📋', 'TOPICS', t));
  }
  if (d.decisions?.length) parts.push(section('✅', 'DECISIONS',
    d.decisions.map((item) => `- ${item.decision}${item.context ? ' — ' + item.context : ''}`).join('\n')));
  if (d.action_items?.length) parts.push(section('🎯', 'ACTION ITEMS',
    d.action_items.map((a) => `- ${[a.owner, a.task, a.due_date].filter(Boolean).join(' → ')}`).join('\n')));
  if (d.open_questions?.length) parts.push(section('❓', 'OPEN QUESTIONS', bullets(d.open_questions)));
  if (d.next_steps?.length) parts.push(section('🔜', 'NEXT STEPS', bullets(d.next_steps)));
  return join(parts);
}

function renderVoiceNote(d) {
  const parts = [];
  parts.push(tldr(d));
  if (d.gist) parts.push(section('💡', 'GIST', d.gist));
  if (d.threads?.length) {
    const t = d.threads.map((th) => {
      let s = th.theme || '';
      if (th.thoughts?.length) s += (s ? '\n' : '') + th.thoughts.map((x) => `  - ${x}`).join('\n');
      return s;
    }).filter(Boolean).join('\n\n');
    parts.push(section('🧵', 'THREADS', t));
  }
  if (d.ideas?.length) parts.push(section('💡', 'IDEAS', bullets(d.ideas)));
  if (d.todos?.length) parts.push(section('☑️', 'TO-DOs',
    d.todos.map((t) => `- ${t.task}${t.context ? ' — ' + t.context : ''}`).join('\n')));
  if (d.questions_to_self?.length) parts.push(section('❓', 'QUESTIONS TO SELF', bullets(d.questions_to_self)));
  return join(parts);
}

function renderFieldNotes(d) {
  const parts = [];
  parts.push(tldr(d));
  if (d.summary) parts.push(section('📝', 'SUMMARY', d.summary));
  if (d.observations?.length) parts.push(section('👁️', 'OBSERVATIONS',
    d.observations.map((o) => {
      let s = `- ${o.location_detail ? o.location_detail + ' — ' : ''}${o.observation}`;
      if (o.photo_reference) s += ` [${o.photo_reference}]`;
      return s;
    }).join('\n')));
  if (d.measurements_and_data?.length) parts.push(section('📏', 'MEASUREMENTS',
    d.measurements_and_data.map((m) => `- ${m.item}: ${m.value}${m.unit ? ' ' + m.unit : ''}`).join('\n')));
  if (d.issues_identified?.length) parts.push(section('⚠️', 'ISSUES',
    d.issues_identified.map((i) => {
      let s = `- [${i.severity || '?'}] ${i.issue}`;
      if (i.location_detail) s += ` — ${i.location_detail}`;
      if (i.recommended_action) s += ` → ${i.recommended_action}`;
      return s;
    }).join('\n')));
  if (d.punch_list?.length) parts.push(section('📋', 'PUNCH LIST',
    d.punch_list.map((p) =>
      `- ${p.item}${p.responsible_party ? ' — ' + p.responsible_party : ''}${p.due_date ? ' | ' + p.due_date : ''}`
    ).join('\n')));
  if (d.follow_ups_needed?.length) parts.push(section('🔜', 'FOLLOW-UPS', bullets(d.follow_ups_needed)));
  return join(parts);
}

function renderPresentation(d) {
  const parts = [tldr(d)];
  if (d.executive_summary) parts.push(section('📝', 'EXECUTIVE SUMMARY', d.executive_summary));
  if (d.thesis) parts.push(section('🎯', 'THESIS', d.thesis));
  if (d.outline?.length) parts.push(section('📋', 'OUTLINE', d.outline.map((s) => {
    let o = s.section || ''; if (s.key_points?.length) o += '\n' + s.key_points.map((p) => `  - ${p}`).join('\n');
    if (s.evidence?.length) o += '\n  Evidence: ' + s.evidence.join('; '); return o;
  }).filter(Boolean).join('\n\n')));
  if (d.key_terms?.length) parts.push(section('📖', 'KEY TERMS',
    d.key_terms.map((t) => `- ${t.term}: ${t.definition}`).join('\n')));
  if (d.quotes?.length) parts.push(section('💬', 'QUOTES',
    d.quotes.map((q) => `"${q.quote}"${q.timestamp ? ' [' + q.timestamp + ']' : ''}`).join('\n')));
  if (d.references?.length) parts.push(section('📚', 'REFERENCES',
    d.references.map((r) => `- ${r.name}${r.context ? ' — ' + r.context : ''}`).join('\n')));
  if (d.qa_highlights?.length) parts.push(section('❓', 'Q&A',
    d.qa_highlights.map((q) => `Q: ${q.question}\nA: ${q.answer}`).join('\n\n')));
  if (d.takeaways?.length) parts.push(section('🎯', 'TAKEAWAYS', bullets(d.takeaways)));
  return join(parts);
}

function renderPunchList(d) {
  const parts = [];
  let summaryText = d.summary || '';
  if (d.total_items) {
    summaryText += (summaryText ? '\n' : '') + `Total items: ${d.total_items}`;
    if (d.completion_estimate) summaryText += ` | Completion: ${d.completion_estimate}`;
  }
  if (summaryText) parts.push(section('📝', 'SUMMARY', summaryText));
  if (d.items?.length) parts.push(section('📋', 'ALL ITEMS',
    d.items.map((i) => {
      let s = `#${i.item_number} [${i.severity || '?'}] ${i.description}`;
      const meta = [
        i.location_or_area ? `📍 ${i.location_or_area}` : '',
        i.trade_or_responsible_party ? `🔧 ${i.trade_or_responsible_party}` : '',
        i.due_date ? `⏰ ${i.due_date}` : '',
      ].filter(Boolean).join(' | ');
      if (meta) s += `\n   ${meta}`;
      if (i.notes) s += `\n   ${i.notes}`;
      return s;
    }).join('\n\n')));
  if (d.by_trade?.length) parts.push(section('🔧', 'BY TRADE',
    d.by_trade.map((t) => `${t.trade} (${t.count} items)\n  ${(t.items || []).join(', ')}`).join('\n')));
  if (d.by_area?.length) parts.push(section('📍', 'BY AREA',
    d.by_area.map((a) => `${a.area} (${a.count} items)\n  ${(a.items || []).join(', ')}`).join('\n')));
  if (d.critical_items?.length) parts.push(section('🚨', 'CRITICAL ITEMS', bullets(d.critical_items)));
  if (d.follow_ups?.length) parts.push(section('🔜', 'FOLLOW-UPS', bullets(d.follow_ups)));
  if (d.next_walk_date) parts.push(`Next walk: ${d.next_walk_date}`);
  return join(parts);
}

function renderUnclassified(d) {
  const parts = [];
  parts.push(tldr(d));
  if (d.summary) parts.push(section('📝', 'SUMMARY', d.summary));
  if (d.key_points?.length) parts.push(section('🔑', 'KEY POINTS', bullets(d.key_points)));
  if (d.people_mentioned?.length) parts.push(section('👤', 'PEOPLE MENTIONED', bullets(d.people_mentioned)));
  if (d.action_items_or_todos?.length) parts.push(section('☑️', 'ACTION ITEMS / TO-DOs',
    d.action_items_or_todos.map((a) => `- ${a.task}${a.context ? ' — ' + a.context : ''}`).join('\n')));
  if (d.questions_raised?.length) parts.push(section('❓', 'QUESTIONS RAISED', bullets(d.questions_raised)));
  if (d.notable_moments?.length) parts.push(section('📌', 'NOTABLE MOMENTS',
    d.notable_moments.map((m) => `- ${m.note}${m.timestamp ? ' [' + m.timestamp + ']' : ''}`).join('\n')));
  return join(parts);
}

function renderGeneric(d) {
  const parts = [tldr(d)];
  const sum = d.summary || d.tldr || d.gist || d.executive_summary;
  if (sum) parts.push(section('📝', 'SUMMARY', sum));
  for (const k of ['key_points', 'topics', 'events_of_the_day', 'wins']) {
    if (d[k]?.length) { parts.push(section('📋', k.replace(/_/g, ' ').toUpperCase(),
      bullets(d[k].map((x) => typeof x === 'string' ? x : x.name || x.topic || JSON.stringify(x))))); break; }
  }
  for (const k of ['action_items', 'commitments', 'todos']) {
    if (d[k]?.length) { parts.push(section('🎯', 'ACTION ITEMS',
      bullets(d[k].map((x) => typeof x === 'string' ? x : x.task || x.commitment || JSON.stringify(x))))); break; }
  }
  return join(parts);
}

function renderToPlainText(mode, data) {
  try {
    switch (mode) {
      case 'meeting':      return renderMeeting(data);
      case 'voice_note':   return renderVoiceNote(data);
      case 'field_notes':  return renderFieldNotes(data);
      case 'punch_list':   return renderPunchList(data);
      case 'presentation': return renderPresentation(data);
      case 'unclassified': return renderUnclassified(data);
      default:             return renderGeneric(data);
    }
  } catch (err) {
    return `📝 SUMMARY\n${data?.summary || '(no summary)'}\n\n(Render error: ${err.message})${FOOTER}`;
  }
}

module.exports = { renderToPlainText, FOOTER };
